nodeLinker: node-modules

enableGlobalCache: true

enableScripts: true

enableStrictSsl: false

networkSettings:
  enableNetwork: true
  httpTimeout: 60000

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
